version: "3"

services:
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    volumes:
      - ./database/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - 3306:3306

  backend:
    build: .
    container_name: backend
    volumes:
      - ./backend:/usr/app
    ports:
      - "3333:3333"
    command: adonis serve --dev
    depends_on:
      - "database"
    links:
      - database:database

  app:
    build: .
    container_name: app
    volumes:
      - ./app:/usr/app
    ports:
      - "3000:3000"
    command: yarn start
    depends_on:
      - "backend"
    links:
      - backend:backend